### ISSUE TITLE
api_token expired problem...

### ISSUE THREAD

**Issue by c0nger** [niyuna/kancolle_echor#2]
instead for question, Used to be always grateful. thanks for your project ;-)

but.... I have a problem with "api_token expired" ;-(....

Mon May 19 18:21:25 2014 # DEBUG # CALLAPISUB # api_token expired
Mon May 19 18:21:25 2014 # INFO # CALLAPI # api /kcsapi/api_port/port failed, retrying attempt 0

I try to use latest token and server, member_id in this kancolle_echor,

(extract time :  May 19 18:20)

modify kancolle_echor.py in config, and created "api_token" file into project folder...

but "api_token expired" error can't solved.....

I do not know why.... ;-(... please check....

**Comment by niyuna** [comment]
Thank you for your feedback.
Does this error always occur or just occasionally? The most possible reason for this is your member_id, this string is used to calculate `api_port` in `port` request. The server will check this string using your member_id and current time, if it's wrong, you will get api token expired from the server. The member_id is a 8-digit string, are you sure you get it correctly from a `port` request?

**Comment by c0nger** [comment]
thanks for your fast feedback ;-)

by the way,

i extract from http://125.6.189.247/kcsapi/api_port/port, in Post data..... Patterns is ->
{"api_member_id":16048**_,"api_id":3,"api_value":1750} (**_ is number)

and API_TOKEN extract from http://125.6.189.247/kcs/mainD2.swf?api_token=bec0729***de569ceb6ddfc05aa574**********&api_starttime=140050221****

is it correct extract from POST/GET data?

and error is always occur... ;-(....

here is error message :

Mon May 19 21:32:46 2014 # INFO # PORT # ***_1284942312904**_*\* (\* is number...)
Mon May 19 21:32:47 2014 # DEBUG # CALLAPISUB # api_token expired
Mon May 19 21:32:47 2014 # INFO # CALLAPI # api /kcsapi/api_port/port failed, retrying attempt 0

**Comment by niyuna** [comment]
you are using the correct way to extact data. It's weird to get this error.

If you are in a hurry, here is a quick solution.
Get a api_port string from the port request and replace the data used in method port of the script with it. If this work, it means maybe different server use different ways to calculate the api_port string.

**Comment by c0nger** [comment]
okay I do it right now... thanks!

**Comment by c0nger** [comment]
dear niyuna,

thanks for your advise, I compared with 'api_port in POST data' and 'api_port from your program function', 

there are different each other

ex) api_port in POST data : 1249128494199988217872

crated from your program  : 1249128494194793623333

your Speculation seems to fit!

 I'll hope to this information is good for you ;-)

and my server is : host = '125.6.189.247'

**Comment by niyuna** [comment]
It should be different because the generator use some random number...
And though it works, It's not a permanent solution, Let's see whether kadokawa will fix this in next upgrade.

**Comment by c0nger** [comment]
Thank you for helping me and created this project ;-) i close this issue.... have a nice day! 

buy the way, I make a launcher.py for replace your scheduler.bat

Sooner or later I'll upload to this project.... ^^/ I'll hope to this code is good for your project
