### ISSUE TITLE
port error...

### ISSUE THREAD

**Issue by c0nger** [niyuna/kancolle_echor#4]
dear niyuna,

i have a serious problem with port error... ;-(

my server address is 125.6.189.247

and not working api_port genereted function...

so i tried to use API_PORT in POSTDATA, and fix code... but ... same...

here is my fixed code, am i doing right away?
# 

def generate_api_port():
    """
    # _local3 = ["16o", "1sc", "2j6", "371", "50e", "5dp", "6hi", "89a", "8dc", "9nf", "118"] # core_2_0_1
    _local3 = ["315", "50e", "7ig", "209", "63e", "9c6", "6cj", "3ge", "928", "1h9", "118"]; # core_2_0_9
    u = int(member_id)
    ret = ''
    ret += str(gI(_local3[10]) + (u % gI(_local3[10])))
    ret += str((9999999999 - int(math.floor(tI() / gI(_local3[10]))) - u) \* gI(_local3[(u % 10)]))
    ret += cN() \* 4
    """
# data from POSTDATA

```
ret = '6249655398155506883863'
log('info', 'port', ret)
return ret
```
# new method for api_port

def port():
    api = '/kcsapi/api_port/port'
    #data = {'spi_sort_order':2, 'api_sort_key':5, 'api_port':generate_api_port_dollar()}
    #port : 6249655398155506883863
    data = {'spi_sort_order':2, 'api_sort_key':5, 'api_port':6249655398155506883863,}
    jo = callAPI(api, data)
    if jo is not None:
        log('info', 'port', 'parsing data')
        parse_port(jo['api_data'])
        log('info', 'port', 'ok')
        return True
#     return False

**Comment by niyuna** [comment]
Your code seems to have no problem. Reuse `api_port` may fail because of a tightened restriction of that string on time.
As I mentioned, different server may use different way to generate that string. By decompiling core_xxx.swf from the game, you can write your own method to generate `api_port` using python.

**Comment by c0nger** [comment]
okay... ;-( thanks to feedback to me.... have a nice day
